In [ ]:
# !wget -nc -O dk_2016_raw.csv http://tastselv.ferv.fvm.dk/DFFETILSKUD/f?p=1002:1:8713342471096590:FLOW_EXCEL_OUTPUT_R1193370060391043250_da

In [ ]:
# !wget -nc -O dk_2017_raw.csv https://stoetteoplysninger.naturerhverv.dk/ords/capp/wwv_flow.show?p_flow_id=101&p_flow_step_id=1&p_instance=10806036644374&p_debug=&p_request=FLOW_EXCEL_OUTPUT_R179713248206429297_da

In [2]:
import pandas as pd

In [1]:
YEAR = 2017

In [41]:
def get_year(year):
    df = pd.read_csv('data/dk_%s_raw.csv.gz' % year, encoding='latin-1', delimiter=';', compression='gzip')
    df['year'] = year
    return df

df = get_year(YEAR)
df.head()

,CVR/SE nr.,Navn,Postnr,Region,Kommune,Measure,EU(DKK),National(DKK),Sum(DKK),Totalt(DKK),Unnamed: 10,year
0,NaN,Ivan P. Riddersholm,7200.0,Region Syddanmark,Billund Kommune,Investments in forest area development and imp...,15.061,37.960,53.021,53.021,NaN,2017
1,NaN,Susanne Arent,9631.0,Region Nordjylland,Vesthimmerlands Kommune,Investments in forest area development and imp...,2.992,7.540,10.532,10.532,NaN,2017
2,NaN,Henning Galsgaard Madsen,8800.0,Region Midtjylland,Viborg Kommune,Investments in forest area development and imp...,20.463,51.480,71.943,71.943,NaN,2017
3,NaN,Flemming Lange,4100.0,Region Sjælland,Ringsted Kommune,Investments in forest area development and imp...,5.364,13.520,18.884,18.884,NaN,2017
4,14783105.0,Ole Hansen,4470.0,Region Sjælland,Kalundborg Kommune,Investments in forest area development and imp...,13.845,18.460,32.305,32.305,NaN,2017

In [42]:
df['Navn'].isnull().sum()

1

In [43]:
df.tail()

,CVR/SE nr.,Navn,Postnr,Region,Kommune,Measure,EU(DKK),National(DKK),Sum(DKK),Totalt(DKK),Unnamed: 10,year
159199,34978182.0,Kromandens Græsningslaug I/S,7620.0,Region Midtjylland,Lemvig Kommune,"Basic payment scheme - Title III, Sections 1, ...",78.903,0,78.903,257.494,NaN,2017
159200,34978182.0,Kromandens Græsningslaug I/S,7620.0,Region Midtjylland,Lemvig Kommune,Payment for agricultural practices beneficial ...,42.397,0,42.397,257.494,NaN,2017
159201,34978182.0,Kromandens Græsningslaug I/S,7620.0,Region Midtjylland,Lemvig Kommune,Reimbursement of appropriations carried over f...,1.697,0,1.697,257.494,NaN,2017
159202,34978182.0,Kromandens Græsningslaug I/S,7620.0,Region Midtjylland,Lemvig Kommune,Agri-environment climate - Art. 28,89.719,29.906,119.625,257.494,NaN,2017
159203,NaN,NaN,NaN,NaN,NaN,NaN,7.177.083.824,368.302.754,7.545.386.212,36.482.314.888,NaN,2017

In [44]:
df = df.dropna(subset=['Navn'])

In [45]:
df['year'].value_counts()

2017    159203
Name: year, dtype: int64

In [46]:
df[df['Navn'].str.contains('Anonym')]

,CVR/SE nr.,Navn,Postnr,Region,Kommune,Measure,EU(DKK),National(DKK),Sum(DKK),Totalt(DKK),Unnamed: 10,year
11,NaN,[Anonym - 172432],7830.0,Region Midtjylland,Holstebro Kommune,Investments in forest area development and imp...,2.785,6.480,9.265,9.265,NaN,2017
13,NaN,[Anonym - 168432],6771.0,Region Syddanmark,Esbjerg Kommune,Investments in forest area development and imp...,2.520,3.360,5.880,5.880,NaN,2017
14,NaN,[Anonym - 173178],8766.0,Region Midtjylland,Ikast-Brande Kommune,Investments in forest area development and imp...,2.063,4.800,6.863,6.863,NaN,2017
18,NaN,[Anonym - 171655],6600.0,Region Syddanmark,Vejen Kommune,Investments in forest area development and imp...,2.166,5.040,7.206,7.206,NaN,2017
25,NaN,[Anonym - 169172],9800.0,Region Nordjylland,Hjørring Kommune,Investments in forest area development and imp...,2.682,6.240,8.922,8.922,NaN,2017
34,NaN,[Anonym - 169985],8654.0,Region Midtjylland,Silkeborg Kommune,Investments in forest area development and imp...,2.682,6.240,8.922,8.922,NaN,2017
40,NaN,[Anonym - 168478],7321.0,Region Syddanmark,Vejle Kommune,Investments in forest area development and imp...,2.063,4.800,6.863,6.863,NaN,2017
43,NaN,[Anonym - 168437],5620.0,Region Syddanmark,Assens Kommune,Investments in forest area development and imp...,2.476,5.760,8.236,8.236,NaN,2017
45,NaN,[Anonym - 172385],7760.0,Region Nordjylland,Thisted Kommune,Investments in forest area development and imp...,2.682,6.240,8.922,8.922,NaN,2017
53,NaN,[Anonym - 168424],7330.0,Region Midtjylland,Ikast-Brande Kommune,Investments in forest area development and imp...,2.063,4.800,6.863,6.863,NaN,2017
62,NaN,[Anonym - 173184],6400.0,Region Syddanmark,Sønderborg Kommune,Investments in forest area development and imp...,2.063,4.800,6.863,6.863,NaN,2017
64,NaN,[Anonym - 172374],7950.0,Region Nordjylland,Morsø Kommune,Investments in forest area development and imp...,2.373,5.520,7.893,7.893,NaN,2017
70,NaN,[Anonym - 168429],9430.0,Region Nordjylland,Aalborg Kommune,Investments in forest area development and imp...,2.795,6.480,9.275,9.275,NaN,2017
71,NaN,[Anonym - 173175],6000.0,Region Syddanmark,Kolding Kommune,Investments in forest area development and imp...,2.700,3.600,6.300,6.300,NaN,2017
74,NaN,[Anonym - 173924],8800.0,Region Midtjylland,Viborg Kommune,Investments in forest area development and imp...,2.476,6.240,8.716,8.716,NaN,2017
82,NaN,[Anonym - 170784],9870.0,Region Nordjylland,Hjørring Kommune,Investments in forest area development and imp...,2.166,5.460,7.626,7.626,NaN,2017
88,NaN,[Anonym - 169170],5350.0,Region Syddanmark,Kerteminde Kommune,Investments in forest area development and imp...,2.063,5.200,7.263,7.263,NaN,2017
89,NaN,[Anonym - 170777],8850.0,Region Midtjylland,Viborg Kommune,Investments in forest area development and imp...,2.166,5.460,7.626,7.626,NaN,2017
98,NaN,[Anonym - 168431],9460.0,Region Nordjylland,Jammerbugt Kommune,Investments in forest area development and imp...,1.651,3.840,5.491,5.491,NaN,2017
114,NaN,[Anonym - 172384],9700.0,Region Nordjylland,Brønderslev Kommune,Investments in forest area development and imp...,2.269,5.720,7.989,7.989,NaN,2017
117,NaN,[Anonym - 172381],8831.0,Region Midtjylland,Viborg Kommune,Investments in forest area development and imp...,2.269,5.720,7.989,7.989,NaN,2017
124,NaN,[Anonym - 169174],4000.0,Region Sjælland,Roskilde Kommune,Investments in forest area development and imp...,2.063,5.200,7.263,7.263,NaN,2017
130,NaN,[Anonym - 169167],9760.0,Region Nordjylland,Hjørring Kommune,Investments in forest area development and imp...,2.476,6.240,8.716,8.716,NaN,2017
155,NaN,[Anonym - 173969],8462.0,Region Midtjylland,Århus Kommune,Investments in forest area development and imp...,2.270,5.720,7.990,7.990,NaN,2017
159,NaN,[Anonym - 171604],8462.0,Region Midtjylland,Århus Kommune,Investments in forest area development and imp...,2.063,5.200,7.263,7.263,NaN,2017
163,NaN,[Anonym - 169987],9370.0,Region Nordjylland,Aalborg Kommune,Investments in forest area development and imp...,2.063,5.200,7.263,7.263,NaN,2017
177,NaN,[Anonym - 171607],5800.0,Region Syddanmark,Nyborg Kommune,Investments in forest area development and imp...,2.579,6.500,9.079,9.079,NaN,2017
180,NaN,[Anonym - 173177],3760.0,Region Hovedstaden,Bornholm Kommune,Investments in forest area development and imp...,2.063,5.200,7.263,7.263,NaN,2017
186,NaN,[Anonym - 172386],7323.0,Region Midtjylland,Hedensted Kommune,Investments in forest area development and imp...,2.202,4.848,7.050,7.050,NaN,2017
225,NaN,[Anonym - 175465],7620.0,Region Midtjylland,Lemvig Kommune,Investments in forest area development and imp...,141.269,188.359,329.628,329.628,NaN,2017
...,...,...,...,...,...,...,...,...,...,...,...,...
158244,NaN,[Anonym - 170021],6870.0,Region Midtjylland,Ringkøbing-Skjern Kommune,Exceptional measures - Measures against market...,312,0,312,312,NaN,2017
158388,NaN,[Anonym - 173226],7500.0,Region Midtjylland,Holstebro Kommune,Exceptional measures - Measures against market...,1.853,0,1.853,1.853,NaN,2017
158389,NaN,[Anonym - 170022],6800.0,Region Syddanmark,Varde Kommune,Exceptional measures - Measures against market...,6.109,0,6.109,6.109,NaN,2017
158392,NaN,[Anonym - 169215],8830.0,Region Midtjylland,Viborg Kommune,Exceptional measures - Measures against market...,652,0,652,652,NaN,2017
158405,NaN,[Anonym - 169216],4480.0,Region Sjælland,Kalundborg Kommune,Agri-environment climate - Art. 28,1.433,478,1.910,1.910,NaN,2017
158553,NaN,[Anonym - 171642],6270.0,Region Syddanmark,Tønder Kommune,Exceptional measures - Measures against market...,3.181,0,3.181,3.181,NaN,2017
158560,NaN,[Anonym - 171643],6392.0,Region Syddanmark,Aabenraa Kommune,Exceptional measures - Measures against market...,130,0,130,130,NaN,2017
158562,NaN,[Anonym - 168472],4990.0,Region Sjælland,Guldborgsund Kommune,Exceptional measures - Measures against market...,4.096,0,4.096,4.096,NaN,2017
158572,NaN,[Anonym - 171644],6760.0,Region Syddanmark,Esbjerg Kommune,Exceptional measures - Measures against market...,6.851,0,6.851,6.851,NaN,2017
158573,NaN,[Anonym - 172424],6971.0,Region Midtjylland,Ringkøbing-Skjern Kommune,Exceptional measures - Measures against market...,1.560,0,1.560,1.560,NaN,2017
158579,NaN,[Anonym - 173958],9690.0,Region Nordjylland,Jammerbugt Kommune,Exceptional measures - Measures against market...,1.795,0,1.795,1.795,NaN,2017
158580,NaN,[Anonym - 173227],9000.0,Region Nordjylland,Aalborg Kommune,Exceptional measures - Measures against market...,2.170,0,2.170,2.170,NaN,2017
158581,NaN,[Anonym - 172425],7550.0,Region Midtjylland,Herning Kommune,Exceptional measures - Measures against market...,4.113,0,4.113,4.113,NaN,2017
158582,NaN,[Anonym - 169217],6855.0,Region Syddanmark,Varde Kommune,Exceptional measures - Measures against market...,674,0,674,674,NaN,2017
158583,NaN,[Anonym - 169218],9631.0,Region Nordjylland,Vesthimmerlands Kommune,Exceptional measures - Measures against market...,6.445,0,6.445,6.445,NaN,2017
158584,NaN,[Anonym - 171645],6200.0,Region Syddanmark,Aabenraa Kommune,Exceptional measures - Measures against market...,210,0,210,210,NaN,2017
158587,NaN,[Anonym - 171646],9280.0,Region Nordjylland,Aalborg Kommune,Exceptional measures - Measures against market...,834,0,834,834,NaN,2017
158618,NaN,[Anonym - 173228],6700.0,Region Syddanmark,Esbjerg Kommune,Exceptional measures - Measures against market...,8.847,0,8.847,8.847,NaN,2017
158619,NaN,[Anonym - 171647],9000.0,Region Nordjylland,Aalborg Kommune,Exceptional measures - Measures against market...,1.746,0,1.746,1.746,NaN,2017
158686,NaN,[Anonym - 170833],9000.0,Region Nordjylland,Aalborg Kommune,Exceptional measures - Measures against market...,6.732,0,6.732,6.732,NaN,2017
158841,NaN,[Anonym - 173959],7300.0,Region Syddanmark,Vejle Kommune,Exceptional measures - Measures against market...,5.211,0,5.211,5.211,NaN,2017
158848,NaN,[Anonym - 168473],6800.0,Region Syddanmark,Varde Kommune,Exceptional measures - Measures against market...,4.038,0,4.038,4.038,NaN,2017
158869,NaN,[Anonym - 168482],7200.0,Region Syddanmark,Billund Kommune,Exceptional measures - Measures against market...,2.315,0,2.315,2.315,NaN,2017
158897,NaN,[Anonym - 169223],8500.0,Region Midtjylland,Norddjurs Kommune,Exceptional measures - Measures against market...,4.640,0,4.640,4.640,NaN,2017
159030,NaN,[Anonym - 171653],8800.0,Region Midtjylland,Viborg Kommune,"Basic payment scheme - Title III, Sections 1, ...",3.417,0,3.417,4.965,NaN,2017
159031,NaN,[Anonym - 171653],8800.0,Region Midtjylland,Viborg Kommune,Payment for agricultural practices beneficial ...,1.548,0,1.548,4.965,NaN,2017
159152,NaN,[Anonym - 170028],4000.0,Region Sjælland,Roskilde Kommune,"Basic payment scheme - Title III, Sections 1, ...",4.022,0,4.022,6.699,NaN,2017
159153,NaN,[Anonym - 170028],4000.0,Region Sjælland,Roskilde Kommune,Payment for agricultural practices beneficial ...,1.822,0,1.822,6.699,NaN,2017
159154,NaN,[Anonym - 170028],4000.0,Region Sjælland,Roskilde Kommune,Agri-environment climate - Art. 28,1.146,382,1.528,6.699,NaN,2017
159172,NaN,[Anonym - 172430],4894.0,Region Sjælland,Guldborgsund Kommune,Organic farming - Art. 29,5.416,1.805,7.222,7.222,NaN,2017

In [47]:
import re
from slugify import slugify

def use_id(row):
    if pd.notnull(row['CVR/SE nr.']):
        return 'DK-%s' % row['CVR/SE nr.']
    return 'DK-%s-%s' % (row['Postnr'], slugify(row['Navn']))

NUM_RE = re.compile('\[Anonym - (\d+)\]')
get_id = lambda x: NUM_RE.match(x).group(1)
df['recipient_id'] = df.apply(lambda x: 'DK-%s' % get_id(x['Navn']) if x['Navn'].startswith('[Anonym - ') else
                              use_id(x), 1)
df['Navn'] = df['Navn'].apply(lambda x: '' if x.startswith('[Anonym - ') else x)
df.head()

,CVR/SE nr.,Navn,Postnr,Region,Kommune,Measure,EU(DKK),National(DKK),Sum(DKK),Totalt(DKK),Unnamed: 10,year,recipient_id
0,NaN,Ivan P. Riddersholm,7200.0,Region Syddanmark,Billund Kommune,Investments in forest area development and imp...,15.061,37.960,53.021,53.021,NaN,2017,DK-7200.0-ivan-p-riddersholm
1,NaN,Susanne Arent,9631.0,Region Nordjylland,Vesthimmerlands Kommune,Investments in forest area development and imp...,2.992,7.540,10.532,10.532,NaN,2017,DK-9631.0-susanne-arent
2,NaN,Henning Galsgaard Madsen,8800.0,Region Midtjylland,Viborg Kommune,Investments in forest area development and imp...,20.463,51.480,71.943,71.943,NaN,2017,DK-8800.0-henning-galsgaard-madsen
3,NaN,Flemming Lange,4100.0,Region Sjælland,Ringsted Kommune,Investments in forest area development and imp...,5.364,13.520,18.884,18.884,NaN,2017,DK-4100.0-flemming-lange
4,14783105.0,Ole Hansen,4470.0,Region Sjælland,Kalundborg Kommune,Investments in forest area development and imp...,13.845,18.460,32.305,32.305,NaN,2017,DK-14783105.0

In [48]:
df['recipient_location'] = df.apply(lambda x: '%s, %s' % (x['Kommune'], x['Region']), 1)

df = df.rename(columns={
    'Navn': 'recipient_name',
    'Postnr': 'recipient_postcode',
    'Measure': 'scheme',
    'EU(DKK)': 'amount'
})

df['currency'] = 'DKK'
df['country'] = 'DK'
df['year'] = YEAR
df.head()

,CVR/SE nr.,recipient_name,recipient_postcode,Region,Kommune,scheme,amount,National(DKK),Sum(DKK),Totalt(DKK),Unnamed: 10,year,recipient_id,recipient_location,currency,country
0,NaN,Ivan P. Riddersholm,7200.0,Region Syddanmark,Billund Kommune,Investments in forest area development and imp...,15.061,37.960,53.021,53.021,NaN,2017,DK-7200.0-ivan-p-riddersholm,"Billund Kommune, Region Syddanmark",DKK,DK
1,NaN,Susanne Arent,9631.0,Region Nordjylland,Vesthimmerlands Kommune,Investments in forest area development and imp...,2.992,7.540,10.532,10.532,NaN,2017,DK-9631.0-susanne-arent,"Vesthimmerlands Kommune, Region Nordjylland",DKK,DK
2,NaN,Henning Galsgaard Madsen,8800.0,Region Midtjylland,Viborg Kommune,Investments in forest area development and imp...,20.463,51.480,71.943,71.943,NaN,2017,DK-8800.0-henning-galsgaard-madsen,"Viborg Kommune, Region Midtjylland",DKK,DK
3,NaN,Flemming Lange,4100.0,Region Sjælland,Ringsted Kommune,Investments in forest area development and imp...,5.364,13.520,18.884,18.884,NaN,2017,DK-4100.0-flemming-lange,"Ringsted Kommune, Region Sjælland",DKK,DK
4,14783105.0,Ole Hansen,4470.0,Region Sjælland,Kalundborg Kommune,Investments in forest area development and imp...,13.845,18.460,32.305,32.305,NaN,2017,DK-14783105.0,"Kalundborg Kommune, Region Sjælland",DKK,DK

In [49]:
df = df.drop(['CVR/SE nr.', 'Kommune', 'Region', 'National(DKK)', 'Sum(DKK)', 'Totalt(DKK)', 'Unnamed: 10'], 1)
df.head()

,recipient_name,recipient_postcode,scheme,amount,year,recipient_id,recipient_location,currency,country
0,Ivan P. Riddersholm,7200.0,Investments in forest area development and imp...,15.061,2017,DK-7200.0-ivan-p-riddersholm,"Billund Kommune, Region Syddanmark",DKK,DK
1,Susanne Arent,9631.0,Investments in forest area development and imp...,2.992,2017,DK-9631.0-susanne-arent,"Vesthimmerlands Kommune, Region Nordjylland",DKK,DK
2,Henning Galsgaard Madsen,8800.0,Investments in forest area development and imp...,20.463,2017,DK-8800.0-henning-galsgaard-madsen,"Viborg Kommune, Region Midtjylland",DKK,DK
3,Flemming Lange,4100.0,Investments in forest area development and imp...,5.364,2017,DK-4100.0-flemming-lange,"Ringsted Kommune, Region Sjælland",DKK,DK
4,Ole Hansen,4470.0,Investments in forest area development and imp...,13.845,2017,DK-14783105.0,"Kalundborg Kommune, Region Sjælland",DKK,DK

In [50]:
len(df)

159203

In [51]:
df['amount'] = pd.to_numeric(df['amount'].str.replace('.', '').str.replace(',', '.'))

In [52]:
df['amount'].sum()

7177083824

In [53]:
df.to_csv('dk_%s.csv.gz' % YEAR, index=False, encoding='utf-8', compression='gzip')